# local development configuration for running code in IDE
server:
  port: 9000

spring:
  main:
    allow-circular-references: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spyglassDB
    username: root
    password: root
  h2:
    console:
      enabled: true  
  sql:
    init:
      platform: h2 
  jpa:
    show-sql: true
    
Amazon:
  credentials:
    access-key: ${amazon.credentials.access-key}
    secret-key: ${amazon.credentials.secret-key}
  region: 
    static: us-east-1
  s3:
    imageBucket: listing-api-images
  stack:
    auto : false
    
logging:
  level:
    org:
      springframework: 
        web: DEBUG
        data: DEBUG
        
